## GitLab pipeline to building and running NodeJS app
## AiDO 2020

stages:
  - build

build-push-image:
  stage: build
  image: docker:17-dind
  variables:
    DOCKER_HOST: tcp://127.0.0.1:2375
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:17-dind
      command: ["--insecure-registry=gitlab.34.107.27.159.nip.io"]
  script:
    - mkdir -p /etc/docker/certs.d/$REGISTRY_NAME
    - cp $CA_CRT /etc/docker/certs.d/$REGISTRY_NAME/ca.crt
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY_NAME    
    - docker build -t $REGISTRY_NAME/root/apps .
    - docker push $REGISTRY_NAME/root/apps
    - docker images
    - docker run --name app14 -d $REGISTRY_NAME/root/apps:14v1 
    - docker ps
    - docker logs app14
    - docker stop app14
  tags:
    - aido
