## GitLab pipeline to building and running NodeJS app
## AiDO 2020

stages:
  - build
  - infra

build-push-image:
  stage: build
  image: docker:18.09
  variables:
    DOCKER_HOST: tcp://127.0.0.1:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:18.09-dind
  script:
    #- docker login --insecure-registry -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/group/project/appnode14:v1 .
    #- docker push $CI_REGISTRY/group/project/appnode14:v1
    - docker images
    - docker run --name app14 -d $CI_REGISTRY/group/project/appnode14:v1 
    - docker ps
    - docker logs app14
    - docker stop app14
  tags:
    - aido
